config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "pages#home"

  get '/about', to: 'pages#about'
  get '/quizzes', to: 'pages#index', as: :quizzes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/option.rb
class Option < ApplicationRecord
  belongs_to :question
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :options
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @username = "adora"
  end

  def about
  end

  def index
    @questions = Question.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quizzes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'pages/header' %>
    <%= yield %>
  </body>
</html>

app/views/pages/_header.html.erb
<nav >
    <ul class="navbar">
        <li><%= link_to 'Home', root_path, class:"" %></li>
        <li><%= link_to 'About', about_path, class:"" %></li>
        <li><%= link_to 'Quizzes', quizzes_path %></li>
        <li>Add Quizzes</li>
    </ul>
</nav>

app/views/pages/about.html.erb
<h1>About Quizzes...</h1>

app/views/pages/home.html.erb
<h1>Welcome to Quizzes, <%= @username %>!</h1>

<p>Why did the programmer challenge the computer to a chess match? Because they wanted to see who could checkmate the bugs first!</p>

app/views/pages/index.html.erb
<ol>
    <% @questions.each do |q| %>
        <li><%= q.title %></li>
        
        <div>
            <% q.options.each do |o|%>
                <input type="radio" id="<%= o.option_sentence%>" name="<%= q.title%>" value="<%= o.option_sentence%>" <%= o.answer && "checked" %> >
                <label for="<%= o.option_sentence%>"> <%= o.option_sentence %> </label>
                <br />
            <% end %>
        </div>
    <% end %>
</ol>